### ISSUE TITLE
BaseGems Build #14 fails with crash report

### ISSUE THREAD

**Issue by BakermanLP** [MinecraftModDevelopmentMods/BaseGems#5]
Full Crash Log:
https://pastebin.com/iPFLkqER

Is there another orespawn version needed?

Thanks in advance

Michael (aka BakermanLP)

**Comment by dshadowwolf** [comment]
Current dev-tip of any of BaseGems, Fantasy Metals, Modern Metals, End Metals or Nether Metals requires the most recent version of BaseMetals - in this case I think BaseGems needs an API update. Will get on that soon.

**Comment by jriwanek** [comment]
All the addons will be getting API updates soonish, closing for now as we're aware of the problem, and BGe is nowhere near ready currently anyway.
